### ISSUE TITLE
lingyi

### ISSUE THREAD

**Issue by lingyi-owl** [Puumanamana/CoCoNet#1]
Dear CoCoNet developer,

I am really interested in your tool. I tried to run it on my metagenomic dataset. It failed because of some errors. I don't really understand what the error message means. I wonder if you can help me with the issue.

Thanks!

Best,
Lingyi

My code is:
coconet --fasta path/to/scaffolds.fasta \
--coverage path/to/*.bam \
--output path/to/coconet_output/

The error message is:
Traceback (most recent call last):
  File "/home/lingyi/miniconda3/envs/coconet/bin/coconet", line 10, in <module>
    sys.exit(main())
  File "/home/lingyi/miniconda3/envs/coconet/lib/python3.6/site-packages/coconet/coconet.py", line 41, in main
    preprocess(cfg)
  File "/home/lingyi/miniconda3/envs/coconet/lib/python3.6/site-packages/coconet/coconet.py", line 66, in preprocess
    min_qual=cfg.min_mapping_quality, flag=cfg.flag, fl_range=cfg.fl_range
  File "/home/lingyi/miniconda3/envs/coconet/lib/python3.6/site-packages/coconet/tools.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/lingyi/miniconda3/envs/coconet/lib/python3.6/site-packages/coconet/preprocessing.py", line 216, in bam_list_to_h5
    shutil.rmtree(tmp_dir)
  File "/home/lingyi/miniconda3/envs/coconet/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/lingyi/miniconda3/envs/coconet/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/lingyi/scripts/tmp42'

**Comment by Puumanamana** [comment]
Hi Lingyi,

Sorry I didn't see your message earlier. I should have fixed this issue in a previous update, did you try with the latest version of CoCoNet (how did you install CoCoNet)?

Cédric
