### ISSUE TITLE
H5 file not found error message

### ISSUE THREAD

**Issue by Yangzyangjin** [Puumanamana/CoCoNet#3]
Dear CoCoNet developer,

I am really interested in your tool and installed the tool by following your documents.
I tried to run it on your test dataset but it failed because of some errors.
I don't really understand what the error message means. I wonder if you can help me with the issue.

Thanks!

Best wishes,
Herina Yang

My code is:
 coconet run --fasta tests/sim_data/assembly.fasta 
--coverage tests/sim_data/*.bam 
--output output_test

Traceback (most recent call last):
  File "/root/miniconda3/envs/vamb/bin/coconet", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/vamb/lib/python3.7/site-packages/coconet/coconet.py", line 62, in main
    learn(cfg)
  File "/root/miniconda3/envs/vamb/lib/python3.7/site-packages/coconet/coconet.py", line 197, in learn
    model = load_model(cfg)
  File "/root/miniconda3/envs/vamb/lib/python3.7/site-packages/coconet/dl.py", line 67, in load_model
    input_shapes = config.get_input_shapes()
  File "/root/miniconda3/envs/vamb/lib/python3.7/site-packages/coconet/core/config.py", line 200, in get_input_shapes
    with h5py.File(self.io['h5'], 'r') as handle:
  File "/root/miniconda3/envs/vamb/lib/python3.7/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/root/miniconda3/envs/vamb/lib/python3.7/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/workspace/coconet/CoCoNet/output_test/coverage.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by Puumanamana** [comment]
Hello Yangzyangjin,

What version of coconet did you install? The `--coverage` argument was used in a previous version, and now it's `--bam` 

Since coconet might not throw an error if you have an incorrect argument name, maybe you can also try your same comment by fixing the flag.

**Comment by dyxstat** [comment]
Hello, 

I use the coconut v1.1.0 and meet the same problem that the H5 file can not be found. I downloaded the software through pip.

Best

**Comment by Puumanamana** [comment]
Hi Yuxuan,

Which command did you use?

Cedric

**Comment by dyxstat** [comment]
Thanks for your reply. I find that my problem has been solved in the previous issue.

Best,
Yuxuan
